name: idleminer
description: "TapMine - Tap-to-Earn Mobile Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.0
  
  # State Management
  provider: ^6.1.2
  
  # UI & Fonts
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  
  # Ads
  google_mobile_ads: ^5.3.0
  
  # HTTP Client
  http: ^1.2.2
  
  # Utilities
  get_it: ^8.0.3
  intl: ^0.20.2
  shared_preferences: ^2.3.5
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3

flutter_native_splash:
  color: "#1A1A1A"
  image: assets/icons/app_icon.png
  android_12:
    image: assets/icons/app_icon.png
    color: "#1A1A1A"

flutter:
  uses-material-design: true

  assets:
    - assets/
